### ISSUE TITLE
Error: Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by Flaxoos** [liudonghua123/delete-release-action#1]
This is not described anywhere, if it is indeed required.

config:
```
      - name: Delete Release
        uses: liudonghua123/delete-release-action@v1
        with:
          release_name: ${{ env.VERSION_NAME }}
          suppress_errors: true
```

**Comment by nivin** [comment]
Same problem for me.

**Comment by kostrykin** [comment]
Just add `GITHUB_TOKEN` as in
```yml
      - name: Delete Release
        uses: liudonghua123/delete-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ env.VERSION_NAME }}
          suppress_errors: true
```
