### ISSUE TITLE
Warning: Not Found

### ISSUE THREAD

**Issue by kostrykin** [liudonghua123/delete-release-action#2]
```yml
      - name: Delete release
        uses: liudonghua123/delete-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ github.ref_name }}
          suppress_errors: true
```

produces output:

> Prepare to delete assets: [object Object]
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Warning: Not Found

I have no clue *what* is not found
